# Project conventions

- Keep this project in the parent pnpm workspace. Use `@lab-reporter/ddd-shared` as a normal `workspace:*` dependency.
- Use Storybook for local development. Keep the shared Storybook, Vite, Svelte, TypeScript, and formatting configs imported from shared. Do not add a separate dev server.
- A project can have several components. Register every component's entry, output directory, and Zod config schema in `components.config.ts`. Each wrapper needs a unique custom element tag. Shared also has its own component registry.
- Keep wrappers and stories in `src/wc`. Keep each component's schema and data model in `src/lib/components/<name>`. Create other folders only when they contain files. Do not add `.gitkeep` files.
- Import shared source files through `@lab-reporter/ddd-shared/components/...` and `@lab-reporter/ddd-shared/utils/...`, with their file extensions. Reuse shared components and utilities before adding local copies.
- Use shared `Layout`, `Shell`, and `createGraphic`. The `src` prop is a CSV URL; `config` is a JSON URL. Render the wrapper without a URL guard so an unpublished CMS graphic can receive editor messages.
- `createGraphic` fetches and validates URL data and handles editor synchronization. It reads the first source, preserves its ID and any other sources, and sends local edits back through `graphic-sync.svelte.ts`. Do not duplicate this state or protocol in a component.
- Extend `createShellConfigSchema(defaultConfig)` for titles, subtitles, footnotes, and layout settings. Bind editable shell fields to the graphic's config. Use Shell's `error`, `loading`, `empty`, and `emptyMessage` props for status messages.
- Import public config JSON for defaults and pass it to `createShellConfigSchema`. Keep sample values in the JSON rather than repeating them in schemas.
- Follow the Flourish sidebar and Data tab model. Config controls graph appearance and column bindings. Source defines data values, names, section membership, and group order. Prepare or restrict source data to fit the graph. Do not add config fields to rename, regroup, clean, or transform data when editing the source is simpler. Keep candidate-card filters separate from chart totals. Validate required CSV headers before calculating a chart.
- Config is a CMS form; source is a spreadsheet. Use flat column mappings, clear field titles and descriptions, and arrays of named records. Add explicit `ui:order` metadata because database JSON storage can reorder object keys. The build emits JSON Schema draft-07 for the CMS validator.
- CMS metadata supports `ui:widget`, `ui:enumNames`, and `ui:options`. Use `layout: 'two-column'` for short mappings and `titleKey` with `collapsible: true` for long arrays. Add matching `ui:order` metadata to nested objects when field order matters.
- Use shared `ChipSelector`, `Tooltip`, and `ScrollFade` where they fit. Use Shell's CSS variables for fixed styles and shared `colorSchema` for editable hex colors with the CMS color picker. Keep project-specific theme colors in the project. Shell and Storybook load Roboto Slab before Noto Sans TC.
- Include shared `EmbedCode` in each story, with the registry name and actual custom element tag. Show it in Storybook and CMS iframe previews. Re-export shared Storybook preview and parameters; shared sets `layout: 'fullscreen'`. Rebuild and restart Storybook before checking copied script URLs.
- Run `pnpm check-types`, `pnpm format:check`, and `pnpm build` for affected packages. Check standalone web-component bundles as well as Storybook when browser validation is requested. Do not deploy or publish CMS records unless requested.
